version: 2.1
orbs:
  microscanner: 'aquasecurity/microscanner@0.1.6'
jobs:
  docker-build:
    executor: microscanner/default
    steps:
      - checkout
      - run: 'docker build -t iamkatli/webserver .'
      - run: 'echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin'
workflows:
  scan-image:
    jobs:
      - docker-build
      - microscanner/scan-image:
          requires:
            - docker-build
          context: microscanner
          image: 'iamkatli/webserver'
