version: 2.1
orbs:
  microscanner: 'aquasecurity/microscanner@dev:0.1.1'
jobs:
  docker-build:
    executor: microscanner/default
    steps:
      - checkout
      - run: 'docker build -t iamkatli/webserver'
workflows:
  scan-image:
    jobs:
      - docker-build
      - microscanner/scan-image:
          requires:
            - docker-build
          context: microscanner
          image: 'iamkatli/webserver'
